### ISSUE TITLE
Extend Device Family Packs (DFP) with additional hw device description

### ISSUE THREAD

**Issue by iomint** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#120]
We would like to bring the possibility to further describe the device from an hw point of view in DFP packs . The descriptors would apply to a specific device providing detailed hw characteristics on the pinout, the peripherals, the clock tree and the memory. This additional information could be used to configure a driver sw components.

The proposal introduces two new children elements **_hwdescriptors_** and **_hwdescriptor_** to the /package/devices/family/../device or /package/devices/family/.../device/variant elements with a “name” attribute pointing to a descriptor file

Then the specification would look as described in the attached file
[Extend DFP with additional hw device description.docx](https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/files/8606400/Extend.DFP.with.additional.hw.device.description.docx)
:

**Comment by ReinhardKeil** [comment]
Should we define then also the hwdescriptor file format or would this file be just used by some specialized tools.  If it is just for specialized tools, I would suggest that we add an environment that describes it.
