### ISSUE TITLE
Add Unique Board Identifier to <board> description

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#141]
### Background:
Create a `link` between a physical board being connected to a host via an on board debugger and the corresponding Open-CMSIS-Pack compliant board description such that board (as well as mounted device) information can be automatically selected by tools.
The board vendor creates a 128 bit UUID for each board revision and embeds it in the debugger firmware and the package description as part of the board tag.
[Universally Uniqe Identifier](https://en.wikipedia.org/wiki/Universally_unique_identifier)
Format: 8-4-4-4-12 for a total of 36 characters (32 hexadecimal characters and 4 hyphens). 
For example:
```
    123e4567-e89b-12d3-a456-426614174000
    xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx
```

### Change request:
Add new optional attribute `Buuid` of type string (36 characters long [0-9a-f\-] to the specification of the board element. 
E.g.:
```
   <board Bvendor="MyVendor" Bname="MyName" Brevision="Rev A" Buuid="123e4567-e89b-12d3-a456-426614174000">
```
### Implementation:
E.g. in CMSIS-DAP:
Add a new CMSIS DAP_Info field to return the UUID
Corresponding request for extension in CMSIS-DAP: https://github.com/ARM-software/CMSIS_5/issues/1433

### Known limitations:
In case multiple boards are connected concurrently, the user needs to chose the `active` board from the list of the connected boards.

**Comment by ReinhardKeil** [comment]
Added Attribute "uuid" to boards element in Open-CMSIS-Spec
