### ISSUE TITLE
Align PartType in PACK.xsd to the specification

### ISSUE THREAD

**Issue by silviooliva** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#162]
In the PACK.xsd schema file, the PartType is not aligned to what is reported in the Open-CMSIS-Pack-Spec documentation.
Indeed, while in the documentation we have that the max occurrence of the **feature**, **book** and **environment** elements is unbounded (see [/package/parts/part](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_parts_pg.html#element_part) and the picture below)

![image](https://user-images.githubusercontent.com/35522857/194358391-cf74ede2-7aaf-4735-835e-34bb33998526.png)

in the PACK.xsd schema file, for these elements, the maxOccurs value is not set (so the default value is used, that is 1) 

![image](https://user-images.githubusercontent.com/35522857/194359058-05efcf77-4913-4bae-ac6b-cd939f09cf53.png)

To fix this issue, the [PACK.xsd](https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/blob/main/schema/PACK.xsd) schema should be updated adding  _maxOccurs="unbounded"_ to the feature, book and environment type definitions, as in the picture hereafter:

![image](https://user-images.githubusercontent.com/35522857/194360028-4529ce3d-b20d-4967-9642-92098ea1d0b2.png)

**Comment by jkrech** [comment]
I have fixed the schema.

**Comment by silviooliva** [comment]
Thank you!
