### ISSUE TITLE
CMSIS-Pack extensions for the current Generator concept 

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#168]
In reference to the Generator Proposal here: 
https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Generator%20(Proposal).md

This change request for the CMSIS-Pack Specification focuses on enhancements to the existing concept:

a) Addition of some pre-defined `category` attribute values for the `<file>` element
  - `genSource` source code templates for the generator
  - `genHeader` header file templates for the generator
  - `genParams` parameter templates for the generator
  - `genInfo` / `genAsset` other information files for the generator

Note: files of the above categories are relevant for the generator associated with the component the files belong to. They are ignored by other tools related to project `configuration` and `build`.
 
b) Clarify in the specification that a single generator can be associated with multiple components. In this case the expectation is that the generator is invoked only once and the generator ensures that all selected components associated with this generator are considered.

c) Clarify that the [`$G`](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_generators_pg.html#element_generators) variable is only available in `<command>` and `<argument>` element and is substituted by the `<absolute_filepath>/<context>.cbuild.yml` file on generator invocation following the format described here: https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-CBuild-Format.md

Note: The project management tool is responsible to create an up-to-date `<context>.cbuild.yml` accepting unresolved dependencies, prior to calling the generator selected by the user.

**Comment by jkrech** [comment]
@fred-r @slhultgren please review this set of high priority updates. What am I missing?

**Comment by fred-r** [comment]
LGTM

**Comment by fred-r** [comment]
Can it be integrated in the version 2.0 ?

**Comment by jkrech** [comment]
Added to the specification.

**Comment by jkrech** [comment]
To be implemented in https://github.com/Open-CMSIS-Pack/devtools/issues/722
