### ISSUE TITLE
Add `Hvendor` and `Hname` as attributes of `<accept>`, `<require>` and `<deny>` elements

### ISSUE THREAD

**Issue by silviooliva** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#182]
In the standard, through the [`/package/conditions/condition`](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_conditions_pg.html#element_condition) element and in particular its child elements [`<accept>`](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_conditions_pg.html#element_accept), [`<require>`](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_conditions_pg.html#element_require) and [`<deny>`](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_conditions_pg.html#element_deny), it is possible to describe dependencies on device, processor, board, software components and compilers.
At the moment, however, there is no way to specify a dependency on a hardware part ([`/package/parts/part`](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_parts_pg.html#element_part)).
To cover this lack, the attributes `Hvendor` and `Hname`, defined as in the picture below, should be added to the attribute list of the `<accept>`, `<require>` and `<deny>` elements.

![image](https://user-images.githubusercontent.com/35522857/208388277-814b587d-1c80-4d61-9cab-13cd24283ac3.png)

![image](https://user-images.githubusercontent.com/35522857/208389818-f3c3e494-c868-4795-85cc-05e431dcd3e1.png)

**Comment by jkrech** [comment]
What is the expectations for tools without support for <parts> descriptions if there is conditions associated with components that require a <part>. 
Is it safe to assume that conditions resolved "correctly" when the part condition uses "unknown" attributes e.g. Hvendor and Hname?

**Comment by edriouk** [comment]
Current implementation in CMSIS tools and Eclipse will report an error for an unknown attribute in expression. 
We cannot change that in already available tools.
For future enhancements we correct that behavior:
 - treat any unknown attribute as a filtering one and pass for evaluations since the algorithm does not change: it is in most cases a wildcard match.  
 - reserve some characters for filtering, e.g. 'F' (Feature) and other for dependency, e.g. 'S' (Software) 
However a warning should be issued telling that evaluation might be not fully correct if an attribute is not known .

**Comment by edriouk** [comment]
Three is another problem with filtering on selected parts.
A filtering condition expression can contain any attribute only once.  It matches the values against supplied collection, that also contains only unique names. 
Thus is is currently not possible to supply two selected parts with different Hname values. 
The evaluation algorithm must be extended to match Hname values against a collection of all selected parts (similar as it is done for  components).

**Comment by jkrech** [comment]
@edriouk, at this point we are not planning to add support for  'accept', 'require' and 'deny' in `csolution`, however we need a way to ignore such condition statements with the result that we are displaying more components than intended by the author of the condition.
Is that easily doable?

**Comment by jkrech** [comment]
@edriouk thanks for confirming.
