### ISSUE TITLE
Add clang entry to CompilerEnumType to *.PDSC format

### ISSUE THREAD

**Issue by smartinou** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#184]
In the schema of the .pdsc format (https://raw.githubusercontent.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/v1.7.7/schema/PACK.xsd), add entry "CLANG" as one of the supported TCompiler.

Clang has an ARM backend and should be available for selection.

**Comment by VGRSTM** [comment]
@smartinou I'm with you
Will serve a past comment https://github.com/Open-CMSIS-Pack/devtools/issues/220#issuecomment-1075126945

**Comment by jkrech** [comment]
Adding `clang` to the `CompilerEnumType` raises the expectation that this compiler is supported end to end. The project has agreed at this point to support a subset of tool-chains: GCC, IAR and Arm Compiler.

**Comment by ReinhardKeil** [comment]
Alignment:
  - add `clang` to Open-CMSIS-Pack-Spec so that conditions are extended to support this compiler
  - keep CMSIS-Toolbox support limited to GCC, IAR, AC6 as companies can extended the support of CMSIS-Toolbox with pull requests.

**Comment by VGRSTM** [comment]
Adding [Document how a compiler can be added to CMSIS-Toolbox](https://github.com/Open-CMSIS-Pack/devtools/issues/493) as cross reference

**Comment by smartinou** [comment]
Great, the current alignment fully satisfies my initial request, which was to add it to the CompilerEnumType of Open-CMSIS-Pack-Spec.

There's already some compilers in the list outside of the ones officially supported by CMSIS-Toolbox. I think it's a good thing to have packchk not choke on such a popular compiler, regardless if the toolbox doesn't support it.

Thanks a lot for following up on this and for the link above.
