### ISSUE TITLE
Extending file element with attributes `language` and `scope`

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#186]
Background:
Alternative approach to specifying files that are:
- language (ASM, C, CPP, C-CPP, Link) specific header
- language (ASM, C, CPP, C-CPP, Link) specific include path
- visible vs. hidden header file
- public vs. private include path 
This extension is superseding the accepted proposal https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/28

![FileTypeExtension](https://user-images.githubusercontent.com/8290187/211550113-a8061684-356d-4e5f-9b8a-595e5843ef01.png)

**Comment by massonal** [comment]
Hi,

I'm in favor of this proposal 👍; it would solve both https://github.com/Open-CMSIS-Pack/devtools/issues/620 and #176 wrt my current needs.

Regards,
