### ISSUE TITLE
Feedback on Linker Script File Proposal

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#187]
Please provide feedback for https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Linker%20Script%20File%20(Proposal).md in this issue

**Comment by fred-r** [comment]
First feedback: as you rely on DFP you cannot use the external memories (board level).

**Comment by ReinhardKeil** [comment]
Replaced with https://github.com/Open-CMSIS-Pack/devtools/issues/655
