### ISSUE TITLE
Errors in page describing the  `/package/examples/example/project` element

### ISSUE THREAD

**Issue by silviooliva** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#200]
I just want to signal some errors found in the in page describing the [/package/examples/example/project](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_examples_pg.html#element_example_project) element. They are all typos but could be misleading.

![image](https://user-images.githubusercontent.com/35522857/216274246-a647fd7a-d536-4412-8864-592eccb24e03.png)

**Comment by jkrech** [comment]
As far as I can see this is fixed now:
https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_examples_pg.html#element_example_project

**Comment by silviooliva** [comment]
LGTM.
Thank you, @jkrech.
