### ISSUE TITLE
Re-running generators and dry-run mode - Proposal

### ISSUE THREAD

**Issue by slhultgren** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#206]
Extracting from https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/104.

A **Generator** in the PDSC specification is essentially a black box from the tooling point of view. It will take some inputs, and then produce some output. This output is then included in the project.

The `input` is today not specifiable in the PDSC format.
The `output` is today described in the .GPDSC file that the generator creates.

The use of generated components in a project raises a few questions that we need to clarify on the tool level:
## 1. `When do we need to run the generator`
**Today** a generator is only run manually, and only required when the .gpdsc is missing.

From the end-user point it is expected that generated components are kept up-to-date with changes to the project. This means that if some `input` changes, then the generator may require re-running to provide the latest contents to the generated component.

This means that a generator should require (re-)running if either:
* The .gpdsc is missing (i.e. the first time)
* If any of the `input` is changed
  `input` change detection can be implemented based on file-stat modification date, compared against the .gpdsc file. So if any `input` file is newer than the .gpdsc file, then the generator requires re-running.

## 2. `What will the generator take as input`
A **generator** today can take a `$G` parameter as input, this will point to a .cbuild.yml file describing the project state.
However, this is not the only thing a generator may require from the project.
These additional files that the generator depend on is called `additionalInputs`. 

The complete set of `input` files can then be defined as the combined set of:
* The `$G` input file
* The `additionalInputs` defined for the generator

To define the additionalInputs, it should be possible to define this in the .PDSC using file patterns:
```xml
  <generator>
    <additionalInputs>
      <filePattern>$P/.*/settings.json</filePattern> <!-- cproject level -->
      <filePattern>$S/.*/settings.json</filePattern> <!-- csolution level -->
```
These file patterns can then be evaluated and collected to create the `additionalInputs` set.
Typically these additionalInputs would be used by the PDSC definition to declare files from the Projects that the generator will depend on.

**To be refined:** The expanded list of `additionalInputs` files should be provided to the generator. Preferably in the `cbuild.yml`

## 3. `What does the generator create if it is run`
In 1 and 2, it is now possible to determine if the `input` requires the generator to be re-run, but it is still not certain that this is the right time to create files, at this point the tools may only want to `evaluate dependencies of the would-be-generated-component`.

To allow this this proposal introduces the `dry-run` concept. This allows running generators in a special mode that will not allow creating any files on the file-system. The only output from the generator in this mode is the .GPDSC. 

Dry-run mode can be added to the .pdsc specification by introducing a new attribute `mode` on the `/package/generators/generator/.../argument` element.
* A generator is **dry-run capable** if it provides an `<argument mode="dry-run">--custom-generator-flag-for-dry-run</argument>` element in the PDSC definition.
* If no `mode="dry-run"` attribute is provided for any argument, then the generator does not support dry-run mode.

In the `dry-run mode` it is expected by the generator that it outputs the .GPDSC on `stdout` of the process and ONLY the .gpdsc. Meaning, in the dry-run-mode, error logs, info messages etc, needs to be printed to `stderr` or to files directly to avoid mixing with the `.GPDSC on stdout` information.

Tools can then run generators in `dry-run` mode, parse the GPDSC from stdout, and then analyze dependencies ahead-of-time. This allows tools to determine fully if the generated components are usable immediately, in a "harmless" way, and only when the user commits to using this component can the tools proceed to create the actual files.

**Comment by ErikMallbergSTM** [comment]
PRs for the "mode" attribute for generator arguments are now available: [implementation](https://github.com/Open-CMSIS-Pack/devtools/pull/1028), [spec](https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/pull/242).
