### ISSUE TITLE
[Documentation] FeatureType[n,m] is wrongly displayed as xs:decimal

### ISSUE THREAD

**Issue by slhultgren** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#215]
The online documentation specifies that the n and m fields are `xs:decimal`, while the PACK.xsd is mentioning `xs:string`.

The examples given in the online documentation seems consistent with `xs:string`, so the documentation for n and m should probably be updated (https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#element_feature)

**Comment by silviooliva** [comment]
@jkrech, @slhultgren 

The same is for the `/package/boards/board/feature`.
https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_boards_pg.html#element_board_feature

Attributes `n ` and `m ` are `xs:decimal` in the documentation, while they are `xs:string` in the PACK.xsd.
