### ISSUE TITLE
[Documentation] DebugInterface minOccurs is 0 in xsd and 1 in documentation

### ISSUE THREAD

**Issue by slhultgren** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#216]
https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/blob/main/schema/PACK.xsd#L1511 sets minOccurs as 0, and online documentation mentions 1..*
https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_boards_pg.html#element_board

**Comment by jkrech** [comment]
Online documentation got updated to set minOccurs to 0.
