### ISSUE TITLE
Are links to web pages allowed in the `book` element?

### ISSUE THREAD

**Issue by silviooliva** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#220]
Both in the `/package/boards/board/book` and in the `/package/devices/family/.../book` description it is not clear if the links to web pages can be used.
In the description of the `name` attribute there is only the reference to the file extension of the document and its path in the package.
Instead, in the description of the `public` attribute it is reported: "Links to web pages are assumed to be public." so I'm led to think that also the external URLs can be used.
Could this point be clarified?

If the URLs are allowed, maybe a short sentence like the following one could be added to the description of the `name` attribute:
"The link to a document on an external web site is also allowed."

**Comment by jkrech** [comment]
The straight answer is: YES 
https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_boards_pg.html#element_board_book
https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#element_book

Needs to be extended to explicitly mention the option to specify a `url`.

**Comment by silviooliva** [comment]
Hi @jkrech, if you agree I can open a PR with the explicit mention to the `url` in the `book` element description.

**Comment by jkrech** [comment]
Documentation got updated.
