### ISSUE TITLE
<examples> element: add environment name="cmsis", make <attributes> optional

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#226]
I suggest for the \<examples\> element:

 - deprecate \<attributes\> as this is to my knowledge nowhere used and we should make it easier to publish examples.
 - use environment name=”cmsis" for projects that are using csolution.yml files.

This is how an example would be described:
``` xml
<examples>
   <example name="retarget" folder="example" doc="README.md">
     <description>Simple example retargeting stdout to USART.</description>
     <board name="V2M-MPS2" vendor="ARM"/>
     <project>
       <environment name="cmsis" load="retarget.csolution.yml"/>
     </project>
  </example>
</examples>
```

**Comment by fred-r** [comment]
Hi @ReinhardKeil,

on ST side, we plan to use the ```<examples>``` element to deliver our example projects for IDEs like EWARM.
So, we would like to keep all the existing possibilities of the tag.

By the way, how do you plan to make it possible to deliver csolution/cproject-based projects ?

Thanks & Regards,
Fred

**Comment by ReinhardKeil** [comment]
The environment name="cmsis" would refer to "*.csolution.yml" based projects with the assumption that an compatible IDE can import them.

Does ST use the \<attributes\> that are currently used for examples?  We are nowhere using it (not on web, not in IDEs), and it just makes it more complicated to publish examples.  Most of the information should be anyway in the *.yml files going forward.

**Comment by ReinhardKeil** [comment]
Conclusion on the TRM 11. April 23: make <attributes> optional, but not mandatory.

**Comment by jkrech** [comment]
PACK Specification updated to make attributes in example optional.
environment names are not restricted by the specification.
