### ISSUE TITLE
Adding `image` as child element of the `part` element

### ISSUE THREAD

**Issue by silviooliva** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#246]
Like for the `board` element and since using the `book` element for that is not recommended, it could be useful for the `part` element having a dedicated child element for referencing at least one `part` image.

A solution could be to reuse the `/package/boards/board/image` definition (reported below) adapting it also for the `part`.

![image](https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/assets/35522857/686aa2e1-e3e5-4b71-a210-41f784ee68e8)

**Comment by silviooliva** [comment]
Hi @jkrech, 
if I understand correctly, you are suggesting to define a new `image` element for the `part` (with `top` attribute instead of `large` and `small`), keeping the `image` for the `board` as it is now. 

For the part the expectation is that, if the `image` child element is present, at least one of its attributes needs to be specified.

Anyway, I'll prepare this PR for your review.

**Comment by jkrech** [comment]
@silviooliva, we need to keep the specification of the board unchanged to not break existing descriptions. 
We can have a `clean` specification for the part element, using `top`, `bottom`, `perspective`. I would suggest to make the `top` attribute required, whereas the other two are optional.

**Comment by silviooliva** [comment]
@jkrech, PR https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/pull/250 opened for this issue.
