### ISSUE TITLE
CMSIS-DSP issue

### ISSUE THREAD

**Issue by hosseinb1994** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#258]
Hello, I am using CMSIS-DSP. But I got this error:#error("-DARM_DSP_CONFIG_TABLES no more supported. Use the new initialization functions to let the linker optimize the code size.")
and once I commented ADD_DEFINITIONS(-DARM_DSP_CONFIG_TABLES) in my cmakedile I got this error:Severity	Code	Description	Project	File	Line	Suppression State
Error		ld returned 1 exit status	C:\Users\hosse\sphereprojectbase\SphereProjectBase_RT\SphereProjectBase_RT	C:\Users\hosse\sphereprojectbase\SphereProjectBase_RT\collect2.exe	1	
Could you please advice me how to solve it? 
Thank you

**Comment by hosseinb1994** [comment]
Hello, I replace cmsis-dsp in my project with this cmsis-dsp :https://github.com/ARM-software/CMSIS-DSP/tree/main. Then I got this error: Severity	Code	Description	Project	File	Line	Suppression State
Error	G1142A341	'sqrt_initial_lut_q15' undeclared (first use in this function)	C:\Users\hosse\sphereprojectbase\SphereProjectBase_RT\SphereProjectBase_RT	C:\Users\hosse\sphereprojectbase\SphereProjectBase_RT\lib\CMSIS_5\CMSIS\DSP\Source\FastMathFunctions\arm_sqrt_q15.c	74	
I didn't use sqrt_q15. But I am using ADD_DEFINITIONS(-DARM_DSP_CONFIG_TABLES) in my cmake for optimization. Could you please help me how to solve the error. Becuase once I comment ADD_DEFINITIONS(-DARM_DSP_CONFIG_TABLES) I got this error: Severity	Code	Description	Project	File	Line	Suppression State
Error		ld returned 1 exit status	C:\Users\hosse\sphereprojectbase\SphereProjectBase_RT\SphereProjectBase_RT	C:\Users\hosse\sphereprojectbase\SphereProjectBase_RT\collect2.exe	1

**Comment by ReinhardKeil** [comment]
Hello @hosseinb1994 sorry for the delay here, but this repo is about the Open-CMSIS-Pack PDSC file specification.  
It looks like you raised a similar request here https://github.com/ARM-software/CMSIS-DSP/issues/116.
Has this been answered?

Could you please raise CMSIS-DSP issues in https://github.com/ARM-software/CMSIS-DSP? 

Also, for solving the problem above, we would need to understand a bit more of the tooling that you are using.  Looks like you are using CMake, but unclear is which version and what CMakeList.txt file.
