### ISSUE TITLE
No Tag for schema v1.7.29

### ISSUE THREAD

**Issue by jeromecoutant** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#259]
Very few tag exist:
https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/tags

For example, this link doesn't work:
https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Taxonomy/blob/c25f36f2cda2e30b44c89dae6bbbb9c05f9885e9/CMSIS.Taxonomy.pdsc#L3

Regards,

**Comment by ReinhardKeil** [comment]
Sorry, I don't understand that problem.  Is your issue that we have not given a Tag for the schema change?

The Link works for me.

**Comment by jeromecoutant** [comment]
Hi

Question is: it seems there is no  systematic tag for all available schema ?

Example in the given file, line 3, we can see: https://raw.githubusercontent.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/v1.7.29/schema/PACK.xsd
which doesn't exist

**Comment by JonatanAntoni** [comment]
Just add tags if required. We didn't do proper releases of the schema so far. Instead, the schema version gets increased typically by every single change.

**Comment by jeromecoutant** [comment]
> Just add tags if required. 

Proposition would be to add a tag for all schema used in toolbox?

File with incorrect link has been removed in https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Taxonomy

OK
