### ISSUE TITLE
Cversion attribute in <condition> element does not allow to change major version

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#273]
The Cversion attribute in the `<condition>` element specifies a minimum version. The documentation is unspecific on behavior of major version changes. However with [Semantic versioning](https://semver.org/) the change of MAJOR version number implies an incompatible change. The CMSIS tools implement an algorithm that does not allow to cross MAJOR version (except when an explicit version range is specified with a maxVersion that has a higher major version).

The documentation needs clarification under: 
https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_conditions_pg.html#element_require

Questions:
- there is an inconsistency of the `version` evaluation in element `<requirements>` elements. A pack with a higher major version is accepted. Can you confirm?
- what is the best way to specify that a MAJOR version change is acceptable.  `Cversion=5.6.0:6` is accepted, but what is the actual behaviour.

**Comment by edriouk** [comment]
I can confirm that packs do not follow the MAJOR rule, they got accepted.
In the current implementation only an explicit range can be used to accept greater version.
for the given range  `Cversion=5.6.0:6` all components from 5.6.0 till 6.0.0 are accepted (6.0.1 gets rejected)

We can still modify most of the tools with: 
- user option (command line, preference setting) to ignore MAJOR  rule
- modify version range comparison to use open expressions like `Cversion="5.6.0:"` to explicitly ignore the MAJOR rule

**Comment by edriouk** [comment]
Please note that range `"1.0.0:2.0.0-" `effectively covers all 1.xx.xxx version and excludes any 2.0.0 (even pre-release)
It effectively dose the same job as  `"1.0.0:1.999.999"`  but looks nicer.

**Comment by jkrech** [comment]
@edriouk I had not thought about that !!!

**Comment by ReinhardKeil** [comment]
@edriouk is it today possible to use `Cversion=5.6.0:7.0.0-` in all our tools? Will this be handled as described by you?  If so, we add it also to the documentation, as this topic is a documentation issue.

**Comment by jkrech** [comment]
### Cversion:

Specifies a software component version

**require Cversion:** condition is true if version of component is equal or higher than requested but compatible. According to [Semantic Versioning](https://semver.org/) compatibility requires the **major version** to remain unchanged.

**deny Cversion:** condition is true if version of component is lower than requested.

Version ranges are specified with `min_version:max_version`. The condition is true if the version of the component is equal or higher than `min_version` and lower or equal than `max_version`. If min_version and max_version are equal the version must match exactly. 

Only specifying the min_version `Cversion="4.1.0"` is identical to specifying the version range `Cversion="4.1.0:5.0.0-0"`

**Comment by edriouk** [comment]
@ReinhardKeil , semantic versioning works consistently across our tools, including `Cversion=5.6.0:7.0.0-`
