### ISSUE TITLE
[spec] Add attribute `overview` to `<package>` level `<description>` element for file reference document

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#291]
The CMSIS-Pack overview document shall provide end user information outlining the content shipped as part of a pack. 
(It is not intended to be a many page product documentation)

```xml
<package ... >
  <vendor>...</vendor>
  <name>...</name>
  <description overview="doc/pack_overview.md">...</description>
  ...
</package>
```

The attribute `overview` contains a file reference which is relative to the pdsc file, to a document in the pack, that gives a single page outline view of the pack content. This file is intended for display/rendering on web pages.
The aim is to keep the <description> of a pack brief and provide further details in the overview document.
While this is an optional attribute it is highly recommended to provide pack overview documents.

Supported file formats discovered by file extensions:
ASCII:  *.txt
PDF: *.pdf
Markdown: *.md
HTML: *.htm / *.html

**Comment by ReinhardKeil** [comment]
only specified Markdown files for now as we need to consider the infrastructure that displays the content as well. I would like to minimize the efforts here.
