### ISSUE TITLE
Component <file> element changes

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#292]
This is a proposal for changes to https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_components_pg.html#element_file

- allow `select` attribute also for `category="header"` file even if `attr` attribute is not `template`. In this case the `select` attribute provides a brief description of the header file. This will improve IDE selection of header where one component offers to choose from multiple independent APIs.
- unify `scope` attribute to just `public` and `private` for both `category="header"` and `category="include"` deprecating `hidden` and `visible`. (Note, `category` is not currently used by any public pack)

**Comment by jkrech** [comment]
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/setup.md#extend-header-with-select
Implement support as part of setup command: https://github.com/Open-CMSIS-Pack/devtools/issues/1322
