### ISSUE TITLE
Introduce feature NPU for <device>

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#293]
Many devices offer today an NPU accelerator. 
Add feature type=NPU to support that. 

https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#element_feature

**Comment by jkrech** [comment]
added `NPU` here:
https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#DeviceFeatureTypeEnum
