### ISSUE TITLE
Allow components that only contain a generator

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#297]
To start a generator, a component may look like this:

```xml
  <component generator="CubeMX" Cclass="Device" Cgroup="CubeMX" Cversion="0.9.0">
      <description>Configure device or board with STM32CubeMX</description>
  </component>
```
It should be therefore accepted to have a component that contains no files.

**Comment by jkrech** [comment]
The downside of lifting this restriction in the schema is that people may add "empty components".
My suggestion previously was to add documentation to the generator component.
```
<files>
  <file category="doc" name="path/to/generator/CubeMX/generator flow documentation" />
</files>
```

**Comment by ReinhardKeil** [comment]
Works for me.  I think we can close this issue then.
