### ISSUE TITLE
Extend clayers element with 'path' and 'copy-to' attributes

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#305]
Proposed changes to [clayer element](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_clayers_pg.html#element_clayer):

  - There should be **additional** attributes that copy layers.

Attribute    | Description                   | Type          | Use
:------------|--------------------------|-------------|------------
path| Path to the directory that contains the layer | xs:string | required
file   | Name of the *.clayer.yml file  (optional with relative path to the directory specified with path) | xs:string | required
copy-to | Path that used to copy the layer into the csolution project (default is attribute path) | xs:string | optional

 - Change the parent element to `<csolution>` as this can also store templates (see #306)
 - Remove <description> as there is already a `description:` node in the `*.clayer.yml` file.

Examples:

```xml
<csolution> 
  <clayer path="layers/board/FRDM-MCXA153-MW" file="Board.clayer.yml" copy-to="board/FRDM-MCXA153" condition="myId" />
  <clayer path="board/FRDM-MCXA153" file="Board.clayer.yml" condition="myId"/>
</csolution>
```

**Comment by RobertRostohar** [comment]
Specifying `copy-to` in the pack pdsc might present some issue. Since there are no explicit rules, the pack creators could use non unique path which would result in overriding files. Should the `copy-to` be actually a tool option rather than specifying it in a pack?
