### ISSUE TITLE
Discuss selection of Template engine used by Open-CMSIS-Pack tools

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#32]
In the context of [#12](https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack/issues/12) the requirement for a template engine was raised.

Identify available open-source template engines which are suitable for generating
- source modules (C/C++/asm, ...)
- header files (C/C++, ...)
- linker scripts 
- other ?

Engines
- [Freemarker](https://freemarker.apache.org/) - e.g. [STM32CubeMX](https://www.st.com/en/development-tools/stm32cubemx.html), [CMSIS-Zone](https://arm-software.github.io/CMSIS_5/latest/Zone/html/index.html)
- [handlebars](https://handlebarsjs.com/)  
- other?

Create a list of Pros and Cons, discuss and agree and create ADR

**Comment by mdortel-stm** [comment]
You can find here a comparison matrix of a log of engines: https://en.wikipedia.org/wiki/Comparison_of_web_template_engines
Even if not strictly true, we can take the first assumption that handlebars is like mustache.

**Comment by fred-r** [comment]
Maybe we should clarify what the templating engine will address ?
I guess we are talking here about the equivalent of CMSIS-Zone in term of features ?
Or is it more than this ?

**Comment by 0xc0170** [comment]
>Maybe we should clarify what the templating engine will address ?

As I read the first comment, source files for a project (not project files like cproject or similar) -  a tool would generate these files based on project configuration. Looking at the templates in CMSIS-Zone, confirms this, source files generated - basically config files, linker file or any other source file that can be generated based on project configuration.

What languages are OK to be used - no requirement there? Looking at freemaker it's written in Java. Handlebars in javascript.

**Comment by fred-r** [comment]
> What languages are OK to be used - no requirement there? Looking at freemaker it's written in Java. Handlebars in javascript.

Good point indeed. What is the technology to be used in this project ?

**Comment by LMESTM** [comment]
@ReinhardKeil  do you mean: "the language that it is written in is _not_ important"  ?

**Comment by jkrech** [comment]
I am closing this issue, as we have concluded to focus on using Handlebars for now.
