### ISSUE TITLE
File Scope Attribute documentation makes reference to non-existent scope

### ISSUE THREAD

**Issue by Quaker762** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#332]
Spotted while browsing here: https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_components_pg.html#FileScopeAttributeType

"Applies only to file elements of category include and category header; ignored otherwise. A private include path is added to the command line for building any module of the component for the specified language. *A hidden header file is indicating an internal header file which must not be explicitly included by modules outside of the scope of the component*."

I can't find this "hidden" scope anywhere in the schema (though I would actually like to use it). Was this removed or is this intended to be added at a later time?

https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/blob/a6d49e51f619dacc89a3763e44e3105561b75169/doxygen/src/components_schema.txt#L1100-L1101

**Comment by jkrech** [comment]
Good catch. Thanks for raising this. This was overlooked when we aligned the naming for header and include paths to `private` and `public`.

**Comment by Quaker762** [comment]
Thanks for getting back to me so quickly @jkrech. So `private` has the same effect as `hidden` then in that it's a component internal header file that isn't exposed to the compiler's include path?

**Comment by jkrech** [comment]
Yes. In addition private header files must not be suggested by tools for addition to a module. Background: there is IDEs suggesting the user to add "#include ..." statement to files in the editor. E.g. if you have selected the CMSIS RTOS2 component the IDE will then suggest to add the header for the RTOS2 component `#include "cmsis_os2.h"` This must not be done for header files that have the attribute "private" set.
