### ISSUE TITLE
Introduction of Export Control Classification element in PDSC

### ISSUE THREAD

**Issue by OCHSTM** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#334]
**Problem to solve**
An open-cmsis pack may be bound to export control: if so, the pack should provide the related Export Control Classification Numbers (ECCN) for both United States & European Union

**Proposed solution**
For this, a change request is proposed to open-cmsis consortium to add an optional `<ECCN>` subsection as a child of the `<package>` element
![image](https://github.com/user-attachments/assets/e02c8ebb-2f30-484a-94ab-03282c2b7a85)

E.g., specifying the ECCN numbers for the stm32u5xx_hal_drivers pack would look like this:
`<package …>`<br/>`  <vendor>STMicroelectronics</vendor>`<br/>`  <name>stm32u5xx_hal_drivers</name>`<br/>`  <ECCN>`<br/>`    <ECCN-EU>NEC</ECCN-EU>`<br/>`    <ECCN-US>5D992.c</ECCN-US>`<br/>`  </ECCN>`

The official web site for ECCN is the following: https://www.bis.doc.gov/index.php/licensing/commerce-control-list-classification/export-control-classification-number-eccn

Within this web site, the following document lists all the codes with a one sentence definition for each item: https://www.bis.doc.gov/index.php/documents/regulations-docs/13-commerce-control-list-index/file

The ECCN codes would be managed through Enums:

- ECCN US codes
![image](https://github.com/user-attachments/assets/6d910c5c-c5eb-466f-a3b1-092d71ae42d5)

- ECCN EU codes
![image](https://github.com/user-attachments/assets/9dd0ee14-6c42-4e26-9647-c8493305fc15)

Please find attached the proposed change for PACK.xsd 1.7.42:
[PACK_xsd_issue_334_v2.zip](https://github.com/user-attachments/files/17632419/PACK_xsd_issue_334_v2.zip)

**Comment by jkrech** [comment]
a) it would be good if we could link from the specification to a public document that describes the meaning of the ECC Numbers
b) I would prefer a shorter tag name instead of `<export-control-classification>` e.g. just `ECCN`

**Comment by OCHSTM** [comment]
> a) it would be good if we could link from the specification to a public document that describes the meaning of the ECC Numbers 

The official web site for ECCN is the following: https://www.bis.doc.gov/index.php/licensing/commerce-control-list-classification/export-control-classification-number-eccn

Within this web site, the following document lists all the codes with a one sentence definition for each item: https://www.bis.doc.gov/index.php/documents/regulations-docs/13-commerce-control-list-index/file

@jkrech Do you think those 2 links would be enough?

> b) I would prefer a shorter tag name instead of `<export-control-classification>` e.g. just `ECCN`

If the ECCN acronym is sufficiently widespread, why not. The pack developer can still refer to the PACK.xsd grammar comments or to the associated documentation to get the meaning  this acronym...
