### ISSUE TITLE
Allow <environment> extension point at <package> level

### ISSUE THREAD

**Issue by OCHSTM** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#335]
**Problem to solve**
Today, the `<environment name=“tool-x”>` element is used to store information specific to the development tool identified by the name attribute. The content below this element is not constrained and thus `<environment name=“tool-x”>` can be seen as an extension point of the PACK.xsd grammar for the tool-x's specific needs.

In current PACK.xsd version (1.7.42), the `<environment name=“tool-x”>` element can only be a child of the following elements:
![image](https://github.com/user-attachments/assets/49f9a40c-0584-4296-969f-ac7682225c8d)

This means there is no way for a pack developer to describe "_tool-x custom information_" that would relate to the whole pack and be applicable to any of the children elements in this pack.

**Proposed solution**
Allow the `<environments>` element to be a child of the `<package>` element.

Please find attached the proposed change for PACK.xsd 1.7.42:
[PACK_xsd_issue_335_v2.zip](https://github.com/user-attachments/files/17629253/PACK_xsd_issue_335_v2.zip)

**Comment by jkrech** [comment]
Reviewing the other occurrences of `<environment>`, this seems to be the only case where a single occurrence is the maximum.
For consistency, we should add an optional `<environments>` tag with one or more child elements `<environment>`

```
                          <!-- list of environments (elements containing information that is specific for a development tool) -->
                          <xs:element name="environments" minOccurs="0" >
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="environment" type="EnvironmentType" minOccurs="1" maxOccurs="unbounded" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
```

**Comment by OCHSTM** [comment]
@jkrech good catch indeed!
