### ISSUE TITLE
Open-CMSIS-Pack / Open-CMSIS-Pack

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#64]
Open-CMSIS-pack is both:
* the name of the organisation
* the name of the repository collecting the specs

This is sometimes not obvious for newcomers to understand what we are referring to.
I assume we cannot really change it ?

**Comment by ReinhardKeil** [comment]
We can rename repositories.  Any suggestion for a name?

**Comment by LMESTM** [comment]
could be open-cmsis-pack-project or open-cmsis-pack-spec ?

**Comment by ReinhardKeil** [comment]
For simplicity we could just name it "specification".

**Comment by LMESTM** [comment]
Fine for me - just mean that when cloning the repo, this will be the default name.

**Comment by ReinhardKeil** [comment]
Good point, for cloning “Open-CMSIS-Pack-spec” might be indeed better, as just "Specification" can be unclear.

**Comment by fred-r** [comment]
Well, the README.md has this title : "CMSIS-Pack"
Can't it be sufficient ?
Or we just need to align the title of the README.

**Comment by jeromecoutant** [comment]
Hi
Maybe it could be good to do the same thing with:
- devtools  ==> Open-CMSIS-Pack-devtools  ?
- cpackget ==> Open-CMSIS-Pack-cpackget ?

**Comment by ReinhardKeil** [comment]
It is not that easy to change the directory structure.  With `devtools` we have everything in one place.

**Comment by ReinhardKeil** [comment]
Closing this as the initial request is resolved and renaming of tools is more difficult that it appears.
