### ISSUE TITLE
Specification of Public attribute on board <book> and <image> elements results in unexpected behaviour

### ISSUE THREAD

**Issue by willlordarm** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#70]
The public attribute on <book> and <image> elements is [documented](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_boards_pg.html#element_board_book) as follows:

| Attribute | Description | Type | Use |
| --- | --- | --- | --- |
| public | Set publishing permissions for the documentation. If <public> is true, then the vendor gives permission to extract the documentation from the Pack and publish it on a web-page. Links to web pages are assumed to be public. The default value is false. | xs:boolean | optional |

The intended goal here was to allow for a vendor to block the display of a given asset on third party web properties. However, a strict interpretation of the specification and documentation results in many images and documents being treated as non-public. Any pdsc that does not specify the public attribute on book or image elements is treated as non-public by default.

Discussion with @KeilChris and others suggests this was not the intention of the specification and does not reflect pack vendor's understanding of how assets will be treated.

**Suggested fix**

1) Update the documentation and schema to clarify that all all images / books that do not have the public attribute set to false will be treated as public by default.
2) Update the schema (if required) to enforce this rule
3) Communicate the change in behaviour to existing pack vendors (since we do not know that _everyone_ interpreted the behaviour in the way we are suggesting it's possible some vendors expect images to remain non-public by virtue of non-inclusion of the attribute).

**Comment by ReinhardKeil** [comment]
Will thanks for this proposal.  I will add this to tomorrows meeting.
