### ISSUE TITLE
Separation of component identification and classification​      ​

### ISSUE THREAD

**Issue by DavidJurajdaNXP** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#94]
Component identification should guarantee identifier uniqueness, but it should be also simple in order to be user friendly.
Classification could cover variable depth of additional categories in order to provide better navigation in available packs/components.

**Comment by mdortel-stm** [comment]
Could I suggest to follow that discussion with #23 ?

**Comment by ReinhardKeil** [comment]
can this be closed
