### ISSUE TITLE
Alternative paths for user friendly project organization (add project_path attribute to component element)

### ISSUE THREAD

**Issue by DavidJurajdaNXP** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#95]
Combination of base_path​, pack_path​, project_path​ could provide user friendly view in form of flat folder structure in workspace.
Flat folder structure - structure without unnecessary nested folders without files.

**Comment by ReinhardKeil** [comment]
David, thanks for the suggestion.  Could you take the time to create an example, so that we better understand the request.  It can be pretty simple.

Right now we show the Cclass as the identifier for a component group in the project window.  I assume you would like to achieve something similar.

**Comment by tcsunhao** [comment]
@DavidJurajdaNXP , base_path is not the one work for shape project tree view. To provide user friendly view, "project_path" is enough.

**Comment by ReinhardKeil** [comment]
This seems to be related how IDE show software components (see here https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/93#issuecomment-1060349943)

Is this correct?  If not, what is the underlying problem you try to solve?

**Comment by tcsunhao** [comment]
> I believe the requirement here is about that the physical directory structure, allowing to control the destination of files belonging to a component when copied into the project folder (see #93).

Yes, both #95 and #93 are actually consequence of NXP data model "project_path" attribute.

**Comment by DavidJurajdaNXP** [comment]
Let's limit scope of this ticket only to project_path.
project_path = data driven project explorer view

According to preliminary agreement in discussion #93 `project_path` will be introduced into standard, but actual usage will be tool specific.

Project_path must be applied to file paths and also to include paths in order to preserve data integrity.
In case of category="header" there should be way how to disable automatic include path generation.
`<file category="header" name="ports/cmsis-driver/netif/ethernetif.h"/>`

Project path is increasing complexity and in order to guarantee data integrity both layouts must be tested by pack vendor. It is price for this feature.

About the "Project View". I think it might be useful to have actually more views in IDE:
- component based view - showing content of components
- file based view - showing physical code organization in folders

I would call it views on different levels of abstraction. Another level might be "CMSIS layers".

**Comment by tcsunhao** [comment]
Agreed with @DavidJurajdaNXP , there can be 2 views in IDE workspace project tree
1. component layout.
    cclass, cgroup, csub can be used for this. With this information, developers can directly know the provenance and classification of the component(which pack it belongs to)
![image](https://user-images.githubusercontent.com/3381677/159421720-3ba63a0c-f69f-4526-9538-35b5bf4e1d37.png)
2. source tree layout
   project_path can be used to contruct it. 
   It is an organization of the source under a component. Sometimes it could be untidy if sources are placed flat, like
![image](https://user-images.githubusercontent.com/3381677/159422133-8a41ec23-c48f-4666-938d-b1cf83f0a376.png)

**Comment by fred-r** [comment]
We support this request.
For most of the packs we need: https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/106

But we will deliver our example projects as packs.
And in these packs, we want the files to be copied in the user section of the project.
It is a bit like attr=template but we want it:
- for files that are not template but source and header
- mandatory (copy by the tool)
- flexible: indicate the path

**Comment by jkrech** [comment]
Change Request:
add component attribute "project_path". The implementation is optional and tools specific and will not change the virtual view.

@DavidJurajdaNXP and @tcsunhao  can you please validate this summary.
It is my understanding that this attribute is somewhat comparable to https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/30 however affecting all configuration files of a component, rather than being specified on a per file basis and it only affects the path but not the filename.

**Comment by tcsunhao** [comment]
@jkrech , Thanks for approving this formally.

The project_path will affect all configuration files as well as other files when NXP tools use it to construct standalone project.

**Comment by tcsunhao** [comment]
@jkrech , Thanks for approving this formally.

The project_path will affect all configuration files as well as other files when NXP tools use it to construct standalone project.

**Comment by fred-r** [comment]
I understand that you want to fill 2 needs:
1. "simplify" the IDE view by applying project_path instead of the real file system path that can be longer
2. create a "standalone folder" with all the necessary files copied according to the project_path organization

But, the point which is unclear to me is: what about files going into RTE folder ?
Do you still put them in RTE folder ?

By the way, I assume this is an optional attribute.

**Comment by jkrech** [comment]
@fred-r, I think you are misunderstanding the feature suggested by @tcsunhao .
The `projectPath` attribute can be used by `tools` to copy both the `config files` as well as the `component files`  of a component into a physical subdirectory of the project directory as specified by `projectPath`. The config files are copied along the component files and not into any <RTE> directory.
The expectation is that a "virtual view" will continue display the files related to a component, and not the physical location of files on disk.

**Comment by tcsunhao** [comment]
Thanks for the explanation of @jkrech which is accurate and complete. 
The projectpath is optional. Default value could be the real physical path of file. 
Related files inside RTE folder, like startup_MK64F12.s(whose NXP project path is "startup"), in real folder, it is located in RTE\iar\Device\MK64FN1M0VLL12, in project explorer view, it can be showed listed inside "startup".
