### ISSUE TITLE
Component should support exclude some files inside from compile

### ISSUE THREAD

**Issue by tcsunhao** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#99]
There is such case that developers want certain file inside one component is excluded from compiled. There are many reasons, a common one is some c source file is just for demo an alternative usage.

**Comment by ReinhardKeil** [comment]
https://arm-software.github.io/CMSIS_5/Pack/html/pdsc_components_pg.html#element_file
category="other" or "template" does that already.  template is a source file that might be added by the user.
